server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://192.168.38.130:3306/test_shop?useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.gis.entity

#showSql
logging:
  level:
    com:
      gis:
        mapper : debug